### ISSUE TITLE
Typical sweets of Mexico

### ISSUE THREAD

**Issue by ARI2001** [PFLC/AprendoGit#68]

**Comment by ItzelMM8** [comment]
Los dulces típicos Mexicanos ademas de deliciosos son también una obra de arte culinario. Coloridos, incorporando tradiciones coloniales y prehispánicas son un reflejo de nuestra rica cultura. He aquí algunos de los dulces mas populares.
1.Pepitorias
Las pepitorias están elaboradas con obleas de harina de trigo, pepitas y miel de piloncillo.
2.Alegrías
Las alegrías están elaboradas con semillas de amaranto, originarias de este país. Su preparación consiste en semillas de amaranto que tiene un alto valor proteico y miel.
3.Palanquetas de Cacahuate
Las palanquetas de cacahuate se elaboran con cacahuates en trozos, agua, glucosa liquida, azúcar, margarina y aceite vegetal.

![fotolia_58310754_xs](https://user-images.githubusercontent.com/36484714/37108817-164f4ab6-21ed-11e8-816f-8e2f32108640.jpg)
